/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String SFUITEXT_BOLD = 'sfuitext_bold';
  static const String SFUITEXT_MEDIUM = 'sfuitext_medium';
  static const String SFUITEXT_REGULAR = 'sfuitext_regular';
  static const String SFUITEXT_SEMIBOLD = 'sfuitext_semibold';
}
